# vim: set fileencoding=utf-8
"""
pythoneda/tools/runtime/flow_inspector_hook/application/flow_inspector_app.py

This file defines the FlowInspectorApp class.

Copyright (C) 2024-today rydnr's pythoneda-tools-runtime/flow-inspector-application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.application import enable, PythonEDA
from pythoneda.shared.artifact.events.infrastructure.cli import (
    ForwardStagedChangesCommittedCli,
)
from pythoneda.shared.artifact.infrastructure.dbus import (
    ArtifactDbusSignalEmitter,
)


# @enable(ForwardStagedChangesCommittedCli)
class FlowInspectorApp(PythonEDA):
    """
    Runs the FlowInspector PythonEDA app.

    Class name: FlowInspectorApp

    Responsibilities:
        - Launches FlowInspector.

    Collaborators:
        - None
    """

    def __init__(self):
        """
        Creates a new FlowInspectorApp instance.
        """
        # python_dep_banner is automatically generated by pythoneda-tools-runtime-def/flow-inspector-application
        try:
            from pythoneda.tools.runtime.flow_inspector.application.flow_inspector_banner import (
                FlowInspectorBanner,
            )

            banner = FlowInspectorBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(
        FlowInspectorApp.main(
            "pythoneda.tools.runtime.flow_inspector.application.FlowInspectorApp"
        )
    )
# vim: syntax=python ts=4 sw=4 sts=4 tw=79 sr et
# Local Variables:
# mode: python
# python-indent-offset: 4
# tab-width: 4
# indent-tabs-mode: nil
# fill-column: 79
# End:
